name: Deploy Vue Project to GitHub Pages with LFS

on:
  push:
    branches: [main] # or your default branch

    # ✨ NEW SECTION TO ADD ✨
# This grants the GITHUB_TOKEN the permissions it needs to create the gh-pages branch.
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Build Vue project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Vue CLI and Vite output to 'dist' by default
